Assignments/boolean birds
bhs-intro-to-programming/Alexandermasters71 pull request #2
Opened 2022-09-09 22:13 UTC by Alexandermasters71

2022-09-10 03:53 UTC, gigamonkey requested changes
Please fix the argument names in the `isRed` and related functions. And also run the "Format document" command I showed you guys to clean up some minor formatting issues. Then I'll re-review and no doubt approve this.

2022-09-10 03:53 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +const isRed = (redburd) => {
As a style note, it's worth thinking about the names of arguments. `redburd` in addition to the cutesy spelling, kinda implies that the bird is red. Which obviously is the question this function is trying to answer. So I'd expect the variable name to be something like `name`, `species`, or `bird` to give some kind of indication what kind of value we are expecting. It's not a big deal in a small function like this but using good names is one of the most powerful tools we have to make our code understandable so it's good to get in the habit early of always spending the time to come up with good names.

2022-09-12 22:11 UTC, Alexandermasters71 commented
@gigamonkey I redid the 'redburd' thing

2022-09-13 02:48 UTC, gigamonkey approved these changes
Looks good. Ship it!

2022-09-19 21:53 UTC, merged